### ISSUE TITLE
Allow config file location to be specified using a cli tag

### ISSUE THREAD

**Issue by SasSwart** [SasSwart/gin-in-a-can#8]
This is necessary in order to be able to integrate gin-in-a-can into ci pipelines where the config file might be part of a different repo in a different directory.

**Comment by alexthemayers** [comment]
Working on this one currently

**Comment by alexthemayers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow config file location to be specified using a cli tag](https://trello.com/c/IXn9Mkw9/1-allow-config-file-location-to-be-specified-using-a-cli-tag)

**Comment by SasSwart** [comment]
Done
